parent=keycloak.v2
import=common/keycloak

styles=css/clinivault-admin.css

logo=logo.svg
logoUrl=/
favIcon=/favicon.svg
favIconType=image/svg+xml

title=Clinivault - Admin Console
description=Manage Clinivault identity and access.
